  apiVersion: v1
  kind: Service
  metadata:
    name: mongo
    namespace: karsajobs
  spec:
    clusterIP: None
    ports:
      - port: 27017
        targetPort: 27017
    selector:
      app: mongodb
  