apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: karsajobs
data:
  mongo.conf: |
    storage:  
      dbPath: /data/db
    systemLog:
      destination: stdout
      verbosity: 1