apiVersion: v1
kind: Service
metadata:
  name: karsajobs-backend
  namespace: karsajobs
  labels:
    app: karsajobs
spec:
  selector:
    app: karsajobs
  type: LoadBalancer
  loadBalancerIP: 34.101.155.19
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP