apiVersion: v1
kind: Service
metadata: 
  name: karsajobs-frontend
  namespace: karsajobs
spec:
  type: LoadBalancer
  selector:
    app: karsajobs-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
